# Generated by Django 2.2 on 2019-05-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0008_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('Самовивіз', 'Самовивіз'), ('Доставка', 'Доставка')], default='Самовивіз', max_length=40),
        ),
    ]
