# Generated by Django 2.2 on 2019-05-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0009_auto_20190509_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='firs_name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Прийнятий в обробку', 'Прийнятий в обробку'), ('Виконується', 'Виконується'), ('Оплачено', 'Оплачено')], default='Прийнятий в обробку', max_length=100),
        ),
    ]
